### Prueba de Registro de Usuario
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "usuario4@example.com",
  "password": "password123",
  "name": "Nombre Usuario"
}

### Prueba de Inicio de Sesión
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "usuario4@example.com",
  "password": "password123"
}

### Crear una tarea
POST http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTczMTAwMjA0OCwiZXhwIjoxNzMxMDA1NjQ4fQ.3gC3w2EErPGpveZR8Cmn8hvyXywnKgvqWrfPIYTnKnE
Content-Type: application/json

{
  "title": "Nueva tarea de prueba"
}

### Listar todas las tareas del usuario
GET http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTczMTAwMjA0OCwiZXhwIjoxNzMxMDA1NjQ4fQ.3gC3w2EErPGpveZR8Cmn8hvyXywnKgvqWrfPIYTnKnE

### Actualizar una tarea (reemplaza `1` con el ID real de una tarea)
PUT http://localhost:3000/tasks/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImlhdCI6MTczMDc0NDYzMSwiZXhwIjoxNzMwNzQ4MjMxfQ.yGXKc7KOjLgYtPXs5oTzwfbtDVlCzdioXh9jWf09GRY
Content-Type: application/json

{
  "title": "Título actualizado de la tarea"
}

### Marcar una tarea como completada (reemplaza `1` con el ID real de una tarea)
POST http://localhost:3000/tasks/4/complete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImlhdCI6MTczMDc0NDYzMSwiZXhwIjoxNzMwNzQ4MjMxfQ.yGXKc7KOjLgYtPXs5oTzwfbtDVlCzdioXh9jWf09GRY

### Eliminar una tarea (reemplaza `1` con el ID real de una tarea)
DELETE http://localhost:3000/tasks/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImlhdCI6MTczMDc0NDYzMSwiZXhwIjoxNzMwNzQ4MjMxfQ.yGXKc7KOjLgYtPXs5oTzwfbtDVlCzdioXh9jWf09GRY

### 1. Iniciar el registro de tiempo para una tarea específica
POST http://localhost:3000/time-tracking/start
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTczMTUyNTg5NiwiZXhwIjoxNzMxNTI5NDk2fQ.0PP26bqmvFfg5m2d0ZS7aY7THfjGIuxfrC-fxVXjgBE
Content-Type: application/json

{
  "taskId": "7"
}

### 2. Detener el registro de tiempo de una tarea
POST http://localhost:3000/time-tracking/stop
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTczMTUyNTg5NiwiZXhwIjoxNzMxNTI5NDk2fQ.0PP26bqmvFfg5m2d0ZS7aY7THfjGIuxfrC-fxVXjgBE
Content-Type: application/json

{
  "sessionId": "482778ea-3fa2-4ede-8853-5e88f7d4d484"
}

### 3. Obtener todas las sesiones de trabajo del usuario autenticado
GET http://localhost:3000/time-tracking/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTczMTAwMjA0OCwiZXhwIjoxNzMxMDA1NjQ4fQ.3gC3w2EErPGpveZR8Cmn8hvyXywnKgvqWrfPIYTnKnE


### Obtener Estadísticas Diarias
GET http://localhost:3000/statistics/daily
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTczMTUyNTg5NiwiZXhwIjoxNzMxNTI5NDk2fQ.0PP26bqmvFfg5m2d0ZS7aY7THfjGIuxfrC-fxVXjgBE
Accept: application/json

###

### Obtener Estadísticas Semanales
GET http://localhost:3000/statistics/weekly
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTczMTY5MTMyMywiZXhwIjoxNzMxNjk0OTIzfQ.H6TcQ_V__oKIIJtonPeohS2XMB4JRZIkvju_tTVZlGk
Accept: application/json

### Obtener Recomendaciones
GET http://localhost:3000/recommendations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTczMTY5MTMyMywiZXhwIjoxNzMxNjk0OTIzfQ.H6TcQ_V__oKIIJtonPeohS2XMB4JRZIkvju_tTVZlGk
Accept: application/json
