### Prueba de Registro de Usuario
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "usuario@example.com",
  "password": "password123",
  "name": "Nombre Usuario"
}

### Prueba de Inicio de Sesión
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "usuario@example.com",
  "password": "password123"
}